packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  lucide-react: ^0.294.0
  tailwindcss: ^3.4.1
  eslint: ^8.57.0
  prettier: ^3.2.5
  typescript: ^5.3.3
  next: 15.1.7
  '@types/node': ^20.11.24
  '@types/eslint': ^8.56.2
